### ISSUE TITLE
JS error (Uncaught TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by moddapampe** [datenanfragen/website#1078]
[Bitte gib uns wenn möglich ein bisschen Kontext für Deine Fehlermeldung. Beschreib also z. B., was Du getan hast, bevor der Fehler aufgetreten ist. Bitte entferne auch alle privaten Daten aus den Debuginformationen weiter unten.]

**Debug information:**

```js
{
    "message": "Uncaught TypeError: Failed to fetch",
    "type": "error",
    "colno": 18078,
    "filename": "https://www.datenanfragen.de/js/commons.bundle.gen.js",
    "lineno": 19,
    "error": {
        "message": "Failed to fetch",
        "description": "fetchTemplate() failed.",
        "name": "TypeError",
        "stack": "TypeError: Failed to fetch\n    at g (https://www.datenanfragen.de/js/commons.bundle.gen.js:19:28351)\n    at D (https://www.datenanfragen.de/js/commons.bundle.gen.js:19:31276)\n    at https://www.datenanfragen.de/js/app.bundle.gen.js:19:10403\n    at h (https://www.datenanfragen.de/js/commons.bundle.gen.js:27:1440)\n    at Generator._invoke (https://www.datenanfragen.de/js/commons.bundle.gen.js:27:1193)\n    at Generator.next (https://www.datenanfragen.de/js/commons.bundle.gen.js:27:1803)\n    at n (https://www.datenanfragen.de/js/commons.bundle.gen.js:19:53776)\n    at s (https://www.datenanfragen.de/js/commons.bundle.gen.js:19:53987)\n    at https://www.datenanfragen.de/js/commons.bundle.gen.js:19:54046\n    at new Promise (<anonymous>)",
        "enduser_message": "Beim Laden des Templates ist ein unbekannter Fehler passiert.",
        "context": {
            "template_url": "https://www.datenanfragen.de/templates/de/access-default.txt"
        }
    },
    "defaultPrevented": false,
    "eventPhase": 2,
    "isTrusted": true,
    "returnValue": true,
    "code_version": "1.0.0",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "url": {
        "ancestorOrigins": {},
        "href": "https://www.datenanfragen.de/generator/",
        "origin": "https://www.datenanfragen.de",
        "protocol": "https:",
        "host": "www.datenanfragen.de",
        "hostname": "www.datenanfragen.de",
        "port": "",
        "pathname": "/generator/",
        "search": "",
        "hash": ""
    }
}
```

**Comment by baltpeter** [comment]
Danke für die Meldung! Zu dem Zeitpunkt hatte unsere CDN-Anbieterin gerade kurz Probleme und das Laden von Seiten hat sehr lange gedauert. Ich vermute, dass das der Grund für die Fehlermeldung war und das Problem sich von selbst gelöst hat.

**Comment by mal-tee** [comment]
Da es keine weiteren Meldungen mehr gab, schließe ich das Issue hier mal.
