### ISSUE TITLE
JS error (Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase'))

### ISSUE THREAD

**Issue by KILLERMANTV** [datenanfragen/website#891]
[If applicable, please provide some context for the error, i.e. describe what you did before the error occurred. Please also remove any sensitive information from the debug information below.]

**Debug information:**

```js
{
    "message": "Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')",
    "type": "error",
    "colno": 5581,
    "filename": "https://www.datarequests.org/js/commons.bundle.gen.js",
    "lineno": 25,
    "error": {
        "message": "Cannot read properties of undefined (reading 'toLowerCase')",
        "name": "TypeError",
        "stack": "TypeError: Cannot read properties of undefined (reading 'toLowerCase')\n    at g (https://www.datarequests.org/js/commons.bundle.gen.js:25:5581)\n    at c (https://www.datarequests.org/js/commons.bundle.gen.js:25:17483)\n    at Module.<anonymous> (https://www.datarequests.org/js/general.bundle.gen.js:18:1494)\n    at Module.112 (https://www.datarequests.org/js/general.bundle.gen.js:18:2287)\n    at a (https://www.datarequests.org/js/runtime.gen.js:17:564)\n    at t (https://www.datarequests.org/js/runtime.gen.js:17:433)\n    at Array.r [as push] (https://www.datarequests.org/js/runtime.gen.js:17:296)\n    at https://www.datarequests.org/js/general.bundle.gen.js:18:47"
    },
    "defaultPrevented": false,
    "eventPhase": 2,
    "isTrusted": true,
    "returnValue": true,
    "code_version": "1.0.0",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
    "url": {
        "ancestorOrigins": {},
        "href": "https://www.datarequests.org/generator",
        "origin": "https://www.datarequests.org",
        "protocol": "https:",
        "host": "www.datarequests.org",
        "hostname": "www.datarequests.org",
        "port": "",
        "pathname": "/generator",
        "search": "",
        "hash": ""
    }
}
```

**Comment by baltpeter** [comment]
Thanks for reporting this!

I think this should be the same problem as in #889. Could you please try the build at https://deploy-preview-890--datenanfragen.netlify.app/ and check whether the error still occurs?

**Comment by KILLERMANTV** [comment]
Hello,
Issue #889 has been closed and error does not occur on production url, neither the preview one.
